// src/components/layout/Sidebar.tsx
'use client'

import { useEffect, useState } from 'react'
import { usePathname, useRouter } from 'next/navigation'
import { Network, ChevronsLeft, ChevronsRight, QrCode, Users, Route, AlignRight } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { cn } from '@/lib/utils'
import { useWorkflowsStore } from '@/store/workflows'
import { useWorkflowBuilderStore } from '@/store/workflow-builder'
import { useUIStore } from '@/store/ui'
import UnsavedChangesModal from '@/components/workflow-canvas/UnsavedChangesModal'

// ─── Constants ────────────────────────────────────────────────────────────────

const W = { collapsed: 80, expanded: 320 } as const

const widthTransition = { duration: 0.22, ease: [0.4, 0, 0.2, 1] as const }

const fadeIn  = { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 } }
const fadeInDelayed = { ...fadeIn, transition: { duration: 0.16, delay: 0.08 } }

// ─── Sub-components ────────────────────────────────────────────────────────────

function ModuleIcon() {
  return (
    <img
      src="/icons/trace-module.svg"
      alt="Trace"
      width={48}
      height={48}
      className="shrink-0"
    />
  )
}

function IconTooltip({ label, rect }: { label: string; rect: DOMRect }) {
  return (
    <div
      className="fixed z-50 pointer-events-none flex items-center gap-1.5"
      style={{ top: rect.top + rect.height / 2, left: rect.right + 8, transform: 'translateY(-50%)' }}
    >
      <div style={{ width: 0, height: 0, borderTop: '5px solid transparent', borderBottom: '5px solid transparent', borderRight: '6px solid #101828' }} />
      <span className="bg-overlay text-white text-xs font-semibold px-2.5 py-1.5 rounded-md whitespace-nowrap shadow-lg">
        {label}
      </span>
    </div>
  )
}

function useIconTooltip() {
  const [rect, setRect] = useState<DOMRect | null>(null)
  const handlers = {
    onMouseEnter: (e: React.MouseEvent) => setRect((e.currentTarget as HTMLElement).getBoundingClientRect()),
    onMouseLeave: () => setRect(null),
  }
  return { rect, handlers }
}

function CollapseBtn({ onClick }: { onClick: () => void }) {
  const { rect, handlers } = useIconTooltip()
  return (
    <>
      <button
        onClick={onClick}
        {...handlers}
        className="flex items-center justify-center p-2 rounded-lg border border-border text-text-muted hover:bg-surface transition-colors shrink-0"
      >
        <ChevronsLeft size={20} />
      </button>
      {rect && <IconTooltip label="Réduire" rect={rect} />}
    </>
  )
}

function ExpandBtn({ onClick }: { onClick: () => void }) {
  const { rect, handlers } = useIconTooltip()
  return (
    <>
      <button
        onClick={onClick}
        {...handlers}
        className="flex items-center justify-center p-2 rounded-lg border border-border text-text-muted hover:bg-surface transition-colors"
      >
        <ChevronsRight size={20} />
      </button>
      {rect && <IconTooltip label="Afficher la navigation" rect={rect} />}
    </>
  )
}

function NavIconBtn({
  icon: Icon, label, active, onClick,
}: {
  icon: React.ElementType; label: string; active: boolean; onClick: () => void
}) {
  const { rect, handlers } = useIconTooltip()

  return (
    <>
      <button
        onClick={onClick}
        {...handlers}
        className={cn(
          'flex items-center justify-center w-12 h-12 rounded-[6px] transition-colors',
          active ? 'bg-surface text-text-nav-hover' : 'bg-white text-text-muted hover:bg-surface hover:text-text-nav-hover',
        )}
      >
        <Icon size={24} />
      </button>
      {rect && <IconTooltip label={label} rect={rect} />}
    </>
  )
}

function NavTextBtn({
  icon: Icon, label, active, onClick,
}: {
  icon: React.ElementType; label: string; active: boolean; onClick: () => void
}) {
  return (
    <button
      onClick={onClick}
      className={cn(
        'flex items-center gap-3 w-full px-3 py-2 rounded-[6px] text-base font-semibold transition-colors whitespace-nowrap',
        active
          ? 'bg-surface text-text-nav-hover'
          : 'bg-white text-text-secondary hover:bg-surface hover:text-text-nav-hover',
      )}
    >
      <Icon size={24} className={active ? 'text-text-secondary' : 'text-text-muted'} />
      {label}
    </button>
  )
}

// ─── Sidebar ───────────────────────────────────────────────────────────────────

export default function Sidebar() {
  const pathname   = usePathname()
  const router     = useRouter()
  const init       = useWorkflowsStore((s) => s.init)
  const workflows  = useWorkflowsStore((s) => s.workflows)
  const hasUnsaved = useWorkflowBuilderStore((s) => s.hasUnsavedChanges)
  const markSaved  = useWorkflowBuilderStore((s) => s.markSaved)
  const { sidebarCollapsed: collapsed, toggleSidebar } = useUIStore()

  const [pendingHref, setPendingHref] = useState<string | null>(null)

  useEffect(() => { init() }, [init])

  const workflowMatch = pathname.match(/^\/workflows\/([^/]+)/)
  const workflowId    = workflowMatch?.[1]
  const workflow      = workflowId ? workflows.find((w) => w.id === workflowId) : null
  const isCanvasPage  = pathname === `/workflows/${workflowId}`

  function navigate(href: string) {
    if (isCanvasPage && hasUnsaved && href !== pathname) {
      setPendingHref(href)
    } else {
      router.push(href)
    }
  }

  function handleSaveAndLeave() {
    markSaved()
    if (pendingHref) router.push(pendingHref)
    setPendingHref(null)
  }

  function handleDiscard() {
    if (pendingHref) router.push(pendingHref)
    setPendingHref(null)
  }

  // ─── Inside a workflow ───────────────────────────────────────────────────────

  if (workflow) {
    const base      = `/workflows/${workflow.id}`
    const navGroups = [
      {
        label: 'Configurer',
        items: [
          { href: base,             label: 'Étapes',      icon: AlignRight },
          { href: `${base}/agents`, label: 'Agents',      icon: Users      },
        ],
      },
      {
        label: 'Observer',
        items: [
          // { href: `${base}/dashboard`, label: 'Tableau de bord', icon: Home },
          { href: `${base}/graphe`,   label: 'Traçabilité', icon: Network },
          { href: `${base}/qr-codes`, label: 'QR codes',    icon: QrCode  },
        ],
      },
    ]

    function isActive(href: string) {
      return pathname === href || (href !== base && pathname.startsWith(href + '/'))
    }

    return (
      <>
        <motion.aside
          animate={{ width: collapsed ? W.collapsed : W.expanded }}
          transition={widthTransition}
          className="flex shrink-0 h-full bg-white border-r border-border overflow-hidden"
        >
          {/* Icon rail */}
          <div className={cn(
            'flex flex-col w-[80px] shrink-0 pt-4',
            !collapsed && 'border-r border-border',
          )}>
            {/* Top: expand btn (collapsed only) → module icon → divider */}
            <div className="flex flex-col items-center gap-4 px-2 mb-6">
              <AnimatePresence initial={false}>
                {collapsed && (
                  <motion.div key="expand-btn" {...fadeIn} transition={{ duration: 0.12 }}>
                    <ExpandBtn onClick={toggleSidebar} />
                  </motion.div>
                )}
              </AnimatePresence>
              <ModuleIcon />
              <div className="w-full h-px bg-border" />
            </div>

            {/* Nav: all icons when collapsed, Route only when expanded */}
            <AnimatePresence mode="wait" initial={false}>
              {collapsed ? (
                <motion.div
                  key="all-icons"
                  {...fadeIn}
                  transition={{ duration: 0.12 }}
                  className="flex flex-col gap-2 items-start px-4"
                >
                  {navGroups.flatMap((group) =>
                    group.items.map(({ href, label, icon }) => (
                      <NavIconBtn
                        key={href}
                        icon={icon}
                        label={label}
                        active={isActive(href)}
                        onClick={() => navigate(href)}
                      />
                    ))
                  )}
                </motion.div>
              ) : (
                <motion.div
                  key="route-only"
                  {...fadeIn}
                  transition={{ duration: 0.12 }}
                  className="flex flex-col gap-2 items-start px-4"
                >
                  <NavIconBtn
                    icon={Route}
                    label="Processus"
                    active={false}
                    onClick={() => navigate('/workflows')}
                  />
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Subnav: slides in when expanded */}
          <AnimatePresence>
            {!collapsed && (
              <motion.div
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.16, delay: 0.07 }}
                className="flex flex-col flex-1 min-w-0 px-4 py-4 gap-6 overflow-y-auto"
              >
                <div className="flex items-center justify-between gap-2 shrink-0">
                  <p className="text-xl font-semibold text-text-primary leading-[30px] truncate">
                    {workflow.name}
                  </p>
                  <CollapseBtn onClick={toggleSidebar} />
                </div>

                <div className="flex flex-col gap-6">
                  {navGroups.map((group) => (
                    <div key={group.label} className="flex flex-col gap-3">
                      <p className="text-base font-medium text-text-tertiary leading-6">
                        {group.label}
                      </p>
                      <div className="flex flex-col gap-1">
                        {group.items.map(({ href, label, icon }) => (
                          <NavTextBtn
                            key={href}
                            icon={icon}
                            label={label}
                            active={isActive(href)}
                            onClick={() => navigate(href)}
                          />
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.aside>

        {pendingHref && (
          <UnsavedChangesModal
            onSave={handleSaveAndLeave}
            onDiscard={handleDiscard}
            onCancel={() => setPendingHref(null)}
          />
        )}
      </>
    )
  }

  // ─── Outside a workflow ───────────────────────────────────────────────────────

  const processusActive = pathname === '/workflows' || pathname.startsWith('/workflows/')

  return (
    <motion.aside
      animate={{ width: collapsed ? W.collapsed : W.expanded }}
      transition={widthTransition}
      className="flex flex-col shrink-0 h-full bg-white border-r border-border overflow-hidden"
    >
      <AnimatePresence mode="wait" initial={false}>
        {collapsed ? (
          <motion.div
            key="collapsed"
            {...fadeIn}
            transition={{ duration: 0.12 }}
            className="flex flex-col h-full py-4 gap-6"
          >
            <div className="flex flex-col items-center gap-4 px-2">
              <ExpandBtn onClick={toggleSidebar} />
              <ModuleIcon />
              <div className="w-full h-px bg-border" />
            </div>
            <div className="flex flex-col gap-2 items-start px-4">
              <NavIconBtn
                icon={Route}
                label="Processus"
                active={processusActive}
                onClick={() => router.push('/workflows')}
              />
            </div>
          </motion.div>
        ) : (
          <motion.div
            key="expanded"
            {...fadeInDelayed}
            className="flex flex-col h-full py-4 gap-6"
          >
            <div className="flex items-center gap-3 px-4">
              <ModuleIcon />
              <span className="flex-1 text-xl font-semibold text-text-primary leading-[30px] whitespace-nowrap">
                Trace
              </span>
              <CollapseBtn onClick={toggleSidebar} />
            </div>
            <nav className="px-4">
              <NavTextBtn
                icon={Route}
                label="Processus"
                active={processusActive}
                onClick={() => router.push('/workflows')}
              />
            </nav>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.aside>
  )
}

// src/components/layout/Sidebar.vue
<template>
  <!-- ── Inside a workflow ─────────────────────────────────────────────────── -->
  <template v-if="workflow">
    <aside
      class="flex shrink-0 h-full bg-white border-r border-border overflow-hidden sidebar-width-transition"
      :style="{ width: collapsed ? `${W.collapsed}px` : `${W.expanded}px` }"
    >
      <!-- Icon rail (always 80px wide) -->
      <div :class="cn('relative flex flex-col w-[80px] shrink-0 pt-4', !collapsed && 'border-r border-border')">

        <!-- Expand btn + module icon + divider -->
        <div class="flex flex-col items-center gap-4 px-2 mb-6">
          <IconBtn
            tooltip="Afficher la navigation"
            :class="['transition-opacity duration-150', collapsed ? 'opacity-100' : 'opacity-0 pointer-events-none']"
            @click="uiStore.toggleSidebar()"
          >
            <ChevronsRight :size="20" />
          </IconBtn>
          <img :src="'/icons/trace-module.svg'" alt="Trace" width="48" height="48" class="shrink-0" />
          <div class="w-full h-px bg-border" />
        </div>

        <!-- Nav icons zone: two layers overlapping via absolute -->
        <div class="relative flex-1">
          <!-- Collapsed: all nav icons -->
          <div
            class="absolute inset-x-0 top-0 flex flex-col gap-2 px-4 transition-opacity duration-150"
            :style="{ opacity: collapsed ? 1 : 0, pointerEvents: collapsed ? 'auto' : 'none' }"
          >
            <template v-for="group in navGroups" :key="group.label">
              <NavIconBtn
                v-for="item in group.items"
                :key="item.href"
                :icon="item.icon"
                :label="item.label"
                :active="isActive(item.href)"
                @click="navigate(item.href)"
              />
            </template>
          </div>

          <!-- Expanded: Route (back) icon only -->
          <div
            class="absolute inset-x-0 top-0 flex flex-col gap-2 px-4 transition-opacity duration-150"
            :style="{ opacity: collapsed ? 0 : 1, pointerEvents: collapsed ? 'none' : 'auto' }"
          >
            <NavIconBtn :icon="Route" label="Processus" :active="false" @click="navigate('/workflows')" />
          </div>
        </div>
      </div>

      <!-- Subnav — fades with CSS, no Vue Transition -->
      <div
        class="flex flex-col flex-1 min-w-0 px-4 py-4 gap-6 overflow-y-auto transition-opacity duration-200"
        :style="{ opacity: collapsed ? 0 : 1, pointerEvents: collapsed ? 'none' : 'auto' }"
      >
        <div class="flex items-center justify-between gap-2 shrink-0">
          <p class="text-xl font-semibold text-text-primary leading-[30px] truncate">{{ workflow.name }}</p>
          <IconBtn tooltip="Réduire" @click="uiStore.toggleSidebar()">
            <ChevronsLeft :size="20" />
          </IconBtn>
        </div>

        <div class="flex flex-col gap-6">
          <div v-for="group in navGroups" :key="group.label" class="flex flex-col gap-3">
            <p class="text-base font-medium text-text-tertiary leading-6">{{ group.label }}</p>
            <div class="flex flex-col gap-1">
              <NavTextBtn
                v-for="item in group.items"
                :key="item.href"
                :icon="item.icon"
                :label="item.label"
                :active="isActive(item.href)"
                @click="navigate(item.href)"
              />
            </div>
          </div>
        </div>
      </div>
    </aside>

    <UnsavedChangesModal
      v-if="pendingHref"
      @save="handleSaveAndLeave"
      @discard="handleDiscard"
      @cancel="pendingHref = null"
    />
  </template>

  <!-- ── Outside a workflow ─────────────────────────────────────────────── -->
  <aside
    v-else
    class="relative flex flex-col shrink-0 h-full bg-white border-r border-border overflow-hidden sidebar-width-transition"
    :style="{ width: collapsed ? `${W.collapsed}px` : `${W.expanded}px` }"
  >
    <!-- Collapsed layer -->
    <div
      class="absolute inset-0 flex flex-col py-4 gap-6 transition-opacity duration-150"
      :style="{ opacity: collapsed ? 1 : 0, pointerEvents: collapsed ? 'auto' : 'none' }"
    >
      <div class="flex flex-col items-center gap-4 px-2">
        <IconBtn tooltip="Afficher la navigation" @click="uiStore.toggleSidebar()">
          <ChevronsRight :size="20" />
        </IconBtn>
        <img :src="'/icons/trace-module.svg'" alt="Trace" width="48" height="48" class="shrink-0" />
        <div class="w-full h-px bg-border" />
      </div>
      <div class="flex flex-col gap-2 px-4">
        <NavIconBtn :icon="Route" label="Processus" :active="processusActive" @click="router.push('/workflows')" />
      </div>
    </div>

    <!-- Expanded layer -->
    <div
      class="absolute inset-0 flex flex-col py-4 gap-6 transition-opacity duration-150"
      :style="{ opacity: collapsed ? 0 : 1, pointerEvents: collapsed ? 'none' : 'auto' }"
    >
      <div class="flex items-center gap-3 px-4">
        <img :src="'/icons/trace-module.svg'" alt="Trace" width="48" height="48" class="shrink-0" />
        <span class="flex-1 text-xl font-semibold text-text-primary leading-[30px] whitespace-nowrap">Trace</span>
        <IconBtn tooltip="Réduire" @click="uiStore.toggleSidebar()">
          <ChevronsLeft :size="20" />
        </IconBtn>
      </div>
      <nav class="px-4">
        <NavTextBtn :icon="Route" label="Processus" :active="processusActive" @click="router.push('/workflows')" />
      </nav>
    </div>
  </aside>
</template>

<script setup lang="ts">
import { ref, computed, defineComponent, h, type Component } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Network, ChevronsLeft, ChevronsRight, QrCode, Users, Route, AlignRight } from 'lucide-vue-next'
import { cn } from '~/lib/utils'
import { useWorkflowsStore } from '~/stores/workflows'
import { useWorkflowBuilderStore } from '~/stores/workflow-builder'
import { useUIStore } from '~/stores/ui'
import UnsavedChangesModal from '~/components/workflow-canvas/UnsavedChangesModal.vue'

const W = { collapsed: 80, expanded: 320 } as const

// ─── IconBtn (collapse/expand) avec tooltip CSS ────────────────────────────────

const IconBtn = defineComponent({
  props: { tooltip: { type: String, required: true } },
  emits: ['click'],
  setup(props, { slots, emit }) {
    return () => h('div', { class: 'group relative flex items-center justify-center' }, [
      h('button', {
        onClick: () => emit('click'),
        class: 'flex items-center justify-center p-2 rounded-lg border border-border text-text-muted hover:bg-surface transition-colors shrink-0',
      }, slots.default?.()),
      h('div', { class: 'absolute left-full ml-2 top-1/2 -translate-y-1/2 z-50 pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-100 flex items-center gap-1.5' }, [
        h('div', { style: 'flex-shrink:0;width:0;height:0;border-top:5px solid transparent;border-bottom:5px solid transparent;border-right:6px solid #101828' }),
        h('span', { class: 'bg-overlay text-white text-xs font-semibold px-2.5 py-1.5 rounded-md whitespace-nowrap shadow-lg' }, props.tooltip),
      ]),
    ])
  },
})

// ─── NavIconBtn avec tooltip CSS ──────────────────────────────────────────────

const NavIconBtn = defineComponent({
  props: {
    icon:   { type: Object as () => Component, required: true },
    label:  { type: String, required: true },
    active: { type: Boolean, required: true },
  },
  emits: ['click'],
  setup(props, { emit }) {
    return () => h('div', { class: 'group relative' }, [
      h('button', {
        onClick: () => emit('click'),
        class: cn(
          'flex items-center justify-center w-12 h-12 rounded-[6px] transition-colors',
          props.active ? 'bg-surface text-text-nav-hover' : 'bg-white text-text-muted hover:bg-surface hover:text-text-nav-hover',
        ),
      }, [h(props.icon as any, { size: 24 })]),
      h('div', { class: 'absolute left-full ml-2 top-1/2 -translate-y-1/2 z-50 pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-100 flex items-center gap-1.5' }, [
        h('div', { style: 'flex-shrink:0;width:0;height:0;border-top:5px solid transparent;border-bottom:5px solid transparent;border-right:6px solid #101828' }),
        h('span', { class: 'bg-overlay text-white text-xs font-semibold px-2.5 py-1.5 rounded-md whitespace-nowrap shadow-lg' }, props.label),
      ]),
    ])
  },
})

// ─── NavTextBtn ───────────────────────────────────────────────────────────────

const NavTextBtn = defineComponent({
  props: {
    icon:   { type: Object as () => Component, required: true },
    label:  { type: String, required: true },
    active: { type: Boolean, required: true },
  },
  emits: ['click'],
  setup(props, { emit }) {
    return () => h('button', {
      onClick: () => emit('click'),
      class: cn(
        'flex items-center gap-3 w-full px-3 py-2 rounded-[6px] text-base font-semibold transition-colors whitespace-nowrap',
        props.active ? 'bg-surface text-text-nav-hover' : 'bg-white text-text-secondary hover:bg-surface hover:text-text-nav-hover',
      ),
    }, [
      h(props.icon as any, { size: 24, class: props.active ? 'text-text-secondary' : 'text-text-muted' }),
      props.label,
    ])
  },
})

// ─── Main ─────────────────────────────────────────────────────────────────────

const route   = useRoute()
const router  = useRouter()
const wfStore = useWorkflowsStore()
const builder = useWorkflowBuilderStore()
const uiStore = useUIStore()

wfStore.init()

const collapsed       = computed(() => uiStore.sidebarCollapsed)
const workflowMatch   = computed(() => route.path.match(/^\/workflows\/([^/]+)/))
const workflowId      = computed(() => workflowMatch.value?.[1])
const workflow        = computed(() => workflowId.value ? wfStore.workflows.find((w) => w.id === workflowId.value) : null)
const isCanvasPage    = computed(() => route.path === `/workflows/${workflowId.value}`)
const processusActive = computed(() => route.path === '/workflows' || route.path.startsWith('/workflows/'))

const pendingHref = ref<string | null>(null)

const navGroups = computed(() => {
  const base = `/workflows/${workflow.value?.id}`
  return [
    {
      label: 'Configurer',
      items: [
        { href: base,             label: 'Étapes', icon: AlignRight },
        { href: `${base}/agents`, label: 'Agents', icon: Users      },
      ],
    },
    {
      label: 'Observer',
      items: [
        { href: `${base}/graphe`,   label: 'Traçabilité', icon: Network },
        { href: `${base}/qr-codes`, label: 'QR codes',    icon: QrCode  },
      ],
    },
  ]
})

function isActive(href: string) {
  const base = `/workflows/${workflowId.value}`
  return route.path === href || (href !== base && route.path.startsWith(href + '/'))
}

function navigate(href: string) {
  if (isCanvasPage.value && builder.hasUnsavedChanges && href !== route.path) {
    pendingHref.value = href
  } else {
    router.push(href)
  }
}

function handleSaveAndLeave() {
  builder.markSaved()
  if (pendingHref.value) router.push(pendingHref.value)
  pendingHref.value = null
}

function handleDiscard() {
  if (pendingHref.value) router.push(pendingHref.value)
  pendingHref.value = null
}
</script>
