// src/app/(app)/workflows/[id]/graphe/page.tsx
import { notFound } from 'next/navigation'
import { graphNodes, graphEdges } from '@/data/graph'
import { workflows } from '@/data/workflows'
import GraphPageClient from '@/components/graph/GraphPageClient'

export default async function WorkflowGraphePage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params
  const workflow = workflows.find((w) => w.id === id)
  if (!workflow) notFound()

  return <GraphPageClient nodes={graphNodes} edges={graphEdges} />
}

// src/pages/workflows/[id]/graphe.vue
<template>
  <div v-if="!workflow" class="flex flex-col flex-1 items-center justify-center">
    <p class="text-sm text-text-muted">Processus introuvable.</p>
  </div>
  <GraphPageClient v-else :nodes="graphNodes" :edges="graphEdges" />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import GraphPageClient from '~/components/graph/GraphPageClient.vue'
import { useWorkflowsStore } from '~/stores/workflows'
import { graphNodes, graphEdges } from '~/data/graph'

definePageMeta({ layout: 'app' })

const route = useRoute()
const store = useWorkflowsStore()
store.init()

const workflow = computed(() => store.workflows.find((w) => w.id === route.params.id))
</script>
